### ISSUE TITLE
[code] Design of multi-selection could be improved

### ISSUE THREAD

**Issue by Jakob-Bach** [cs-select-team/CS-Select#116]
In general, it is a good idea to bundle several selections before contacting the ML server if only few features are to be selected, as currently done in `BinarySelect`. However, the existence of sub-rounds, which are not a full part of the object-oriented design, also has disadvantages, e.g. the loose check on the number of selected features in `StandardRound::selectFeatures()` (only guarantees that number of selected features is in range on overage, not for each sub-round). Furthermore, information is lost when storing the selected features in the database, as one cannot see the individual choices of each sub-round any more, but only the selected and displayed features combined over all sub-rounds (For BinarySelect, the main interest of an organiser would be to get exactly the binary decisions). I don't know how much effort it is to introduce sub-rounds properly (in the database it would only be one additional column in the *rounds* table, but in the code it's more complicated).

**Comment by bendixsonnenberg** [comment]
the shownFeatures and chosenFeatures row contains the features in the order in which the player gets to see them( and selects them), so the organizer can infer the binary selections from the order of the features.

**Comment by Jakob-Bach** [comment]
Order can be changed because of sorting (commit dea7e79, issue #79).
