### ISSUE TITLE
Alert is always shown when resetting password when registered with invalid email

### ISSUE THREAD

**Issue by Santaaa348** [cs-select-team/CS-Select#196]
Alert `Unknown email` pops up, even though email is entered correctly and password has changed.

**Comment by SeineEloquenz** [comment]
Works flawlessly for me. Did you use an existing, valid email address? Because my first guess would be that an error occurs sending the e-mail and therefore the alert is shown

**Comment by Santaaa348** [comment]
Well, no I did not. 😅

**Comment by Weitspringer** [comment]
So we have to catch this error and push an according alert

**Comment by SeineEloquenz** [comment]
I don't think we need to change anything here, if I remember correctly the alert is "Unknown email address" or such, which certainly is true for non existing email addresses

**Comment by Santaaa348** [comment]
Well, as of now you can register using invalid email addresses. I just realised there is a tooltip (not localised btw) saying that an `@` is missing, yet you can still create accounts. Is this expected? @Weitspringer

**Comment by SeineEloquenz** [comment]
As far as I know, only email addresses that follow the correct email syntax are allowed, but I believe it was not planned to check whether a correctly formatted email address actually exists.

**Comment by bendixsonnenberg** [comment]
> 
> 
> Well, as of now you can register using invalid email addresses. I just realised there is a tooltip (not localised btw) saying that an `@` is missing, yet you can still create accounts. Is this expected? @Weitspringer

that tooltip is from the browser you are using, not our website.

**Comment by bendixsonnenberg** [comment]
prevented with 
28cbed3b49dcbef3668c6a8318531ec942cae9d6
