### ISSUE TITLE
No success message when inviting players during game creation

### ISSUE THREAD

**Issue by Santaaa348** [cs-select-team/CS-Select#212]
If you don't invite player during game creation, a green alert pops up saying that creation was succesful. 
When I invite a player and then create a game, game will be created, but the `Create` button remains grayed out and no success message appears. Does this occur to you too?

**Comment by bendixsonnenberg** [comment]
can't reproduce

**Comment by Santaaa348** [comment]
Could actually be a problem on my end (even though I do not know why). Someone else please test this and if it does not happen, this can be closed.

**Comment by SeineEloquenz** [comment]
Can't reproduce as well
